# Generated by Django 4.0.3 on 2022-05-11 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbc',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 11, 21, 27, 43, 665664)),
        ),
        migrations.AlterField(
            model_name='filestore',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 11, 21, 27, 43, 665664)),
        ),
        migrations.AlterField(
            model_name='urine',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 11, 21, 27, 43, 665664)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 11, 21, 27, 43, 665664)),
        ),
    ]
