# Generated by Django 4.0.4 on 2022-05-10 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbc',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 12, 13, 52, 758037)),
        ),
        migrations.AlterField(
            model_name='filestore',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 12, 13, 52, 760031)),
        ),
        migrations.AlterField(
            model_name='urine',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 12, 13, 52, 760031)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 10, 12, 13, 52, 755045)),
        ),
    ]
