# Generated by Django 4.0.3 on 2022-05-12 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbc',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 12, 14, 3, 46, 902609)),
        ),
        migrations.AlterField(
            model_name='filestore',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 12, 14, 3, 46, 902609)),
        ),
        migrations.AlterField(
            model_name='urine',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 12, 14, 3, 46, 902609)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 12, 14, 3, 46, 899415)),
        ),
    ]
