# Generated by Django 3.2.7 on 2022-04-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220423_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbc',
            name='hgb_enc',
            field=models.BinaryField(default=None, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='cbc',
            name='mchc_enc',
            field=models.BinaryField(default=None, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='cbc',
            name='mcv_enc',
            field=models.BinaryField(default=None, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='cbc',
            name='mpv_enc',
            field=models.BinaryField(default=None, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='cbc',
            name='pc_enc',
            field=models.BinaryField(default=None, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='cbc',
            name='pcv_enc',
            field=models.BinaryField(default=None, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='cbc',
            name='rcd_enc',
            field=models.BinaryField(default=None, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='cbc',
            name='wbc_enc',
            field=models.BinaryField(default=None, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='cbc',
            name='rbc_enc',
            field=models.BinaryField(default=None, editable=True, null=True),
        ),
    ]
