# Generated by Django 4.0.4 on 2022-04-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_urine'),
    ]

    operations = [
        migrations.AddField(
            model_name='urine',
            name='ketones',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='urine',
            name='reaction',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='urine',
            name='sg',
            field=models.FloatField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='urine',
            name='uro',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
