# Generated by Django 4.0.3 on 2022-04-09 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_comment_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='content',
            new_name='field_name',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='date',
        ),
    ]
