# Generated by Django 3.2.7 on 2022-04-24 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_filestorage'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestorage',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
