# Generated by Django 4.0.3 on 2022-04-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_content_comments_field_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='field_name',
            field=models.TextField(max_length=500),
        ),
    ]
