# Generated by Django 4.0.3 on 2022-04-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220418_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbc',
            name='file',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cbc',
            name='hgb',
            field=models.FloatField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cbc',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cbc',
            name='mchc',
            field=models.FloatField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cbc',
            name='mcv',
            field=models.FloatField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cbc',
            name='mpv',
            field=models.FloatField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cbc',
            name='pc',
            field=models.FloatField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='cbc',
            name='pcv',
            field=models.FloatField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cbc',
            name='rbc',
            field=models.FloatField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cbc',
            name='rcd',
            field=models.FloatField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cbc',
            name='wbc',
            field=models.FloatField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tempfilestorage',
            name='file',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
