# Generated by Django 3.2.7 on 2022-04-24 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_filestorage_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileStorage',
            new_name='FileStore',
        ),
    ]
